### ISSUE TITLE
Create authors list as separate file and include in document structure

### ISSUE THREAD

**Issue by AndyClifton** [LIKE-ITN/FAIR-data-and-Open-Science-principles#1]
We need to make sure the author list is complete and includes contact details.

- [x] @niva83 - could you add your ORCiD details to [0_introduction.md](https://github.com/LIKE-ITN/FAIR-data-and-Open-Science-principles/blob/master/docs/0_introduction.md), please?

Who else needs to be added to the author list?

**Comment by nikokaoja** [comment]
@AndyClifton I will add authors and necessary contact info.

Regarding other authors, basically whoever is going to work on the document will be asked to add his/her name to the authors' list together with the contact info.

**Comment by niva83** [comment]
@AndyClifton regarding other authors, basically whoever is going to work on the document will be asked to add his/her name to the authors' list together with the contact info.

**Comment by AndyClifton** [comment]
Changing issue title; authors were in the introduction. This has been pushed to another file for maintenance.

**Comment by AndyClifton** [comment]
Closing. Now have `docs/authors.md` file.
