### ISSUE TITLE
Review/Update of Research Lifecycle section

### ISSUE THREAD

**Issue by nikokaoja** [LIKE-ITN/FAIR-data-and-Open-Science-principles#6]
@AndyClifton If you could review [Research Lifecycle section](https://github.com/LIKE-ITN/FAIR-data-and-Open-Science-principles/blob/master/docs/1_research_lifecycle.md) that would be great.

**Comment by AndyClifton** [comment]
Major edit done.

Still some questions, though:
- [x] line 50. It's not clear to me why a researcher might publish output without metadata. Could be good to explain.
- [x] The document at the moment reads a bit like a general overview of Open Science (which is useful) but in many places we're lacking a concrete recommendation as to what the LIKE ESRs and others should be doing. Do we need to explain earlier what it means for LIKE? It may be worth adding links through to the use cases.

**Comment by nikokaoja** [comment]
@AndyClifton thanks!

Regarding your questions:

- line 50, many reasons but here are some of them: (1) [metadata will live longer than data](https://www.go-fair.org/fair-principles/a2-metadata-accessible-even-data-no-longer-available/), (2) while you want to announce that you created dataset, you still want to be the first one who has access to it (you could put an embargo, but often because of (1) you want to detach metadata and data or at least to have a sole copy of metadata published without data), (3) you might have data that you cannot share with everyone, but still want to report that you have it and to cite it (i.e., you want unique and persistent identifier of metada).

- point 2, true, however, I have limited time for the deliverable, which is today. The main reason I chose to go with a Git and web site is that I can update content after the 

I am closing this issue.

**Comment by AndyClifton** [comment]
@niva83 I put that text for point 1 in the paper, which is where it belongs.

**Comment by AndyClifton** [comment]
Pushed point 1 to a new issue. Closing
